### ISSUE TITLE
SAVE/RESTORE don't restore loaded gun

### ISSUE THREAD

**Issue by heasm66** [Quuxplusone/Castlequest#13]
I loaded the gun `LOAD GUN` and then my inventory says: `Bullet in gun`. But when I `SAVE `and then `RESTORE` the gun is no longer loaded. This could be a bug in the original too...

**Comment by Quuxplusone** [comment]
Hmm. This works fine for me in OSX and Linux as far as I can tell.
Note that if you `LOAD GUN` and then `DROP GUN`, it unloads itself and splits apart into separate `bullet` and `gun` objects in the room. This seems intentional: there's no distinct "loaded gun" object in the game. Also, this happens regardless of anything you do with SAVE/RESTORE.
If you can reproduce the SAVE/RESTORE behavior you described, please post a transcript here (i.e. what commands you typed from beginning to end of the saved game, and what commands you typed from beginning to end of the restored game).

Per my take on #12: If we find an "original" _Castlequest_ behavior then I'll make a mental note of it but not attempt to "fix" it in the `patches` branch. But if we find that the `patches` branch is behaving differently on Cygwin versus OSX, or that the bug is due to a change in the meaning of the Fortran code since 1980, then I'll try to fix it in `patches`. (If it's due to a transcription typo, I'll fix it in `main` and send you $5. If it's unreproducible, then nothing happens. ;))

**Comment by heasm66** [comment]
You're right. I can't reproduce this any longer and you're description that the bullet and gun gets split if you drop them is probably what happened. I think you can close this issue.
